import app.classes.db.candidate
import app.classes.db.course
import app.classes.db.scores
import app.classes.db.spartan
import app.classes.db.strengths
import app.classes.db.strength_junc
import app.classes.db.tech
import app.classes.db.tech_junc
import app.classes.db.sparta_day
import app.classes.db.trainer
import app.classes.db.weaknesses
import app.classes.db.weaknesses_junc
