from app.classes.db.candidate import Candidate
from app.classes.db.course_staff_junc import CourseStaffJunc
from app.classes.db.course_type import CourseType
from app.classes.db.course import Course
from app.classes.db.location import Location
from app.classes.db.sparta_day import SpartaDay
from app.classes.db.staff import Staff
from app.classes.db.strength_junc import StrenghtJunc
from app.classes.db.strengths import Strengths
from app.classes.db.tech_junc import TechJunc
from app.classes.db.tech import Tech
from app.classes.db.weaknesses_junc import WeaknessesJunc
from app.classes.db.weaknesses import Weaknesses
from app.classes.db.weekly_performance import WeeklyPerformance
