import app.classes.db.candidate
import app.classes.db.course_staff_junc
import app.classes.db.course_type
import app.classes.db.course
import app.classes.db.location
import app.classes.db.sparta_day
import app.classes.db.staff
import app.classes.db.strength_junc
import app.classes.db.strengths
import app.classes.db.tech_junc
import app.classes.db.tech
import app.classes.db.weaknesses_junc
import app.classes.db.weaknesses
import app.classes.db.weekly_performance
